sources:
  - name: yam-gnosis
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/realtoken-thegraph/yam-realt-subgraph-gnosis
  - name: yam-eth
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/realtoken-thegraph/yam-realt-subgraph
  - name: wallet-goerli
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/realtoken-thegraph/realtoken-goerli

documents:
  - ./config/graph/getOffersQuery.graphql