apiVersion: cert-manager.io/v1
kind: ClusterIssuer #To Allow any resource to access this Issue we use "ClusterIssuer"
metadata:
  name: letsencrypt-<ENV_PREFIX>
  namespace: default
spec:
  acme:
    # Email address used for ACME registration
    email: arslan.ahmad14@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-<ENV_PREFIX>
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx